### ISSUE TITLE
"Master site"

### ISSUE THREAD

**Issue by abh** [neilb/history-of-cpan#16]
For a good while FUnet was the "master site". JHI had tools to mirror from other sites into the appropriate places. The modules from PAUSE was just one of the sources. Eventually, as you know PAUSE was the only real source.

funet.fi was running the master site until some point in the last 10 years where we switched it around so the perl.org run mirror was mirroring the modules directly from PAUSE and the rest from Funet. A while later we moved PAUSE to the perl.org servers, too. Since early 2011 the perl.org server has been maintaining all of CPAN.

**Comment by neilb** [comment]
Thanks -- have updated the text based on this. Sorry to be so tardy.
