### ISSUE TITLE
CPAN Testers history

### ISSUE THREAD

**Issue by abh** [neilb/history-of-cpan#17]
For a long time the CPAN Testers "database" was the mailing list archive. The mailing list system, of course, wasn't built to handle millions and millions of messages. Many of the people trying to subscribe to get the stream of messages learned that their mail system wasn't actually so equipped either.

I forget the year, but at some point it was changed to be a proper database with an API instead of the API being "send email here" for writing and "use NNTP or subscribe to the emails" for reading.

**Comment by neilb** [comment]
Thanks. I've added a bit on this. I'm also collecting some stuff on CPAN Testers and Metabase, which will cover some of the points you referred to.

Cheers,
Neil
