### ISSUE TITLE
It is customary for authors to own errors

### ISSUE THREAD

**Issue by nanis** [neilb/history-of-cpan#18]
The document ends with:

> This history was edited by Neil Bowers (NEILB) from a multitude of sources, and email discussions with many of the people listed above. All errors are theirs.

I am confused by this. It is customary for the author of a work to give credit to those who contributed, reviewed etc, but own any remaining errors by saying "all remaining errors are mine." This statement seems to be disclaiming any responsibility for the author, and putting all the onus on the sources and the people listed above.

**Comment by neilb** [comment]
At some point there was a smiley at the end of the "All errors are theirs", but it seems to have been lost.

I'll update that sentence -- thanks.

**Comment by nanis** [comment]
You're right, it would read much more differently with a smiley. Thank you.

**Comment by neilb** [comment]
Fixed for the next version.
